disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Home"

[params]
  displayName = "ğŸ‡¬ğŸ‡§ EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  description = "Business Data Analyst"

[params.author]
  name = "FayÃ§al Bessayah"
  image = "img/photo_profil.jpeg"
  imageQuality = 96
  headline = "Data Analyst | Business Intelligence | AI & Data Science"
  bio = "I share my analyses, experiments, and discoveries about data"
  links = [
    { github = "https://github.com/fbessayah" },
    { linkedin = "https://www.linkedin.com/in/fay%C3%A7al-bessayah-0a4b632b/" },
        { medium = "https://medium.com/@fbessayah/" }
  ]
